Created binary_search.java
khanchi97/Smvdu-Algos pull request #144
Opened 2017-12-12 18:36 UTC by sidntrivedi012

2017-12-13 07:05 UTC, khanchi97 reviewed
I'm in suspect that you have just copy/pasted this code.If what I'm saying is right then please write your code on your own otherwise it will be complained to KWoC.
Also don't forget to add a README file also in your implentations.

2017-12-13 07:06 UTC, khanchi97 requested changes
Make required changes.

2017-12-13 07:32 UTC, sidntrivedi012 commented
Sir,

With all due respect, I have not copied it.I have taken variables like c,
middle etc. so that the readers can get a better understanding of the
concept. I had seen the other method of binary search in a website, so I
mentioned that too for extra information. But still, I am making some
changes. Thank you. Sorry for the inconvenience.

On 13 Dec 2017 12:36 p.m., "Sushil khanchi" <notifications@github.com>
wrote:

> *@khanchi97* requested changes on this pull request.
>
> Make required changes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/khanchi97/Smvdu-Algos/pull/144#pullrequestreview-83076268>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AdvcXfw6UQeQD8ucdPB3F5YXG7vtuCCcks5s_3dZgaJpZM4Q_cNY>
> .
>

2017-12-13 14:03 UTC, khanchi97 commented
okay, no issue.Just wait for collaborators to review this.
@RajaVamsi11 ^

2017-12-13 14:05 UTC, khanchi97 commented
And make a different README file to describe what it does instead adding it to the code, and try to explain how this code is working :)

2017-12-13 14:30 UTC, sidntrivedi012 commented
Sir,

Added Readme.txt for Binary Search Algo. Kindly review. Regards.

2017-12-14 08:55 UTC, khanchi97 requested changes
make required changes.

2017-12-14 08:55 UTC, khanchi97 commented on search-algos/binary_search/binary_search.java
> +    int numbers = new int[n];               //declaring array of n numbers
See the syntax error here.
change this line to
int [] numbers = new int[n];

2017-12-14 09:09 UTC, sidntrivedi012 commented
Made the change.

2017-12-14 13:29 UTC, khanchi97 approved these changes
Thanks for your PR @sidntrivedi012 🎉

2017-12-14 13:29 UTC, merged

2017-12-14 13:36 UTC, sidntrivedi012 commented
Thanks @khanchi97